### ISSUE TITLE
android annotations vs retrofit & co

### ISSUE THREAD

**Issue by equinoxel** [tomkoptel/radiotastic#1]
Hi,

Why did you pick aanotations over the retrofit/butterknife stack?

Cheers,

Laur

**Comment by tomkoptel** [comment]
Hi, Laur!

As far as, I know butterknife was designed superiously to help out with both UI injections and UI callbacks.
For my personal needs or simply speaking "taste" android annotations provides much more enhancements.
- Generates fluent builder pattern API for fragments,activities,services. 
- Introduces convenient way to work with saved instance state fields.
- Nice implementation of composition principles on the basis of `@Bean` annotation.
- Simple to use API for ui and background tasks on the basis `@UIThread` and `@Background` annotations.

In general, I think decision also made,because of myself being used to AAnnotations.

Regarding retrofit...Well as you can see from app dependencies list I'm already utilizing them :)

I hope I've left enough reasoning to you.
Best regards!

**Comment by equinoxel** [comment]
Cool. Thank you very much for this! :)
